# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ${JOB_NAME}
#   namespace: intranet
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: nfs2-csi-prd
#   resources:
#     requests:
#       storage: 150Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: intranet
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs2-csi-prd
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
  namespace: intranet
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs2-csi-prd
  resources:
    requests:
      storage: 5Gi