---
apiVersion: v1
kind: Service
metadata:
  name: ${JOB_NAME}
  namespace: intranet
spec:
  type: ClusterIP
  selector:
    app: ${JOB_NAME}
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
